version: "3.7"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "nexus@123"
      ACCEPT_EULA: "Y"
    volumes: 
      - ./mssql/:/var/opt/mssql
      
volumes:
  mssql-volume:
