version: "3"
services:
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1035:1025 # smtp server
      - 8035:8025 # web ui
    volumes: 
      - ./maildir:/maildir
