---
 version: '3.3'
  
 services:
    sonarqube:
      #depends_on:
      #  - sql-server-db
      image: sonarqube
      command: "-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false"
      ports:
        - "9000:9000"
        - "9092:9092"
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      environment:
       - SONARQUBE_JDBC_URL=jdbc:sqlserver://192.168.66.191:1433;databaseName=sonar
       - SONARQUBE_JDBC_USERNAME=sa
       - SONARQUBE_JDBC_PASSWORD= nexus@123
       - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
 
 volumes:
    
    sonarqube_bundled-plugins:
    sonarqube_conf:
    sonarqube_data:
    sonarqube-extensions:
    sonarqube_extensions:
